language: elixir
env:
  - TRAVIS=true
elixir:
  - 1.9.0
otp_release:
  - 22.0.1
matrix:
  fast_finish: true
addons:
  postgresql: '11.0'
services:
  - postgresql
before_script:
  - ps aux | grep postgres
  - which pg_isready
  - pg_isready
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
script:
  - MIX_ENV=test mix test
after_success:
  - MIX_ENV=dev mix credo
