language: elixir
elixir:
  - 1.9.0
otp_release:
  - 22.0.1
matrix:
  fast_finish: true
addons:
  postgresql: '11.0'
services:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
script:
  - MIX_ENV=test mix test
after_success:
  - MIX_ENV=dev mix credo
