#!/usr/bin/env bash

# MIX_ENV=prod DATABASE_URL=ecto://postgres:postgres@localhost/bmx01_prod SECRET_KEY_BASE=asdf mix release base
MIX_ENV=prod DATABASE_URL=ecto://postgres:postgres@localhost/bmx01_prod SECRET_KEY_BASE=asdf mix distillery.release

